apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heyhey
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jdivine/heyhey.git
    path: helm/heyhey
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: heyhey1
    name: in-cluster
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s