# This is a Github Workflow to perform CI tasks.
# See the `zz-local-ci.sh` script for local CI commands.

on: [push, pull_request]
name: CI Pipeline

permissions:
  contents: read
  packages: write

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Podman
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y podman

            - name: Get Poetry
              uses: snok/install-poetry@v1
              with:
                  version: '2.2.1'
                #   virtualenv: true

            - name : Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12
                  cache: 'poetry'

            - name: Setup Poetry
              run: |
                  poetry env use 3.12

            - name: Install dependencies
              run: |
                bash zz-local-ci.sh deps
            
            - name: Lint code
              run: |
                bash zz-local-ci.sh lint

            - name: Run tests
              run: |
                bash zz-local-ci.sh test

            - name: Build container image
              run: |
                bash zz-local-ci.sh build

            - name: Smoke test container
              run: |
                bash zz-local-ci.sh smoke

            - name: Podman Login
              uses: redhat-actions/podman-login@v1
              with:
                username: ${{ github.repository_owner }}
                password: ${{ github.token }}
                registry: "ghcr.io/${{ github.repository_owner }}"

            - name: Publish to GitHub Container Registry
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

              # In the real world, I'd want to create unique tags based on branch or PR name and existing tags.
              # Just using latest in this example since it's all we need to demonstrate CI and CD.
              # I'd want to publish for PRs (with a PR-specific tag) and for merges to main (with a "production" tag).
              run: |
                bash -x zz-local-ci.sh publish

