# This is a Github Workflow to perform CI tasks.
# See the `zz-local-ci.sh` script for local CI commands.

on: [push, pull_request]
name: CI Pipeline
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Podman
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y podman

            - name: Get Poetry
              uses: snok/install-poetry@v1
              with:
                  version: '2.2.1'
                #   virtualenv: true

            - name : Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12
                  cache: 'poetry'

            - name: Setup Poetry
              run: |
                  poetry env use 3.12

            - name: Install dependencies
              run: |
                bash zz-local-ci.sh deps
            
            - name: Lint code
              run: |
                bash zz-local-ci.sh lint
            - name: Run tests
              run: |
                bash zz-local-ci.sh test
            - name: Build container image
              run: |
                bash zz-local-ci.sh build
            - name: Smoke test container
              run: |
                bash zz-local-ci.sh smoke
